### PR TITLE
Update test_node_leader.py

### PR DESCRIPTION
**Pull request by jseagrave21**
**What current issue(s) does this address, or what feature is it adding?**
- increases coverage
- supports https://github.com/CityOfZion/neo-python/pull/723

I wanted to see what you thought before I kept working. Also, I tried experimenting with `ACCEPT_INCOMING_PEERS` and found that our current implementation will not work. Also, I didn't include it because I could not get the tests to pass in `make test`.
First, I recommend in `Shutdown` and `Restart` we use logic something like this
```
if self.listening_server:
    self.listening_server.stopListening()
```
where `listening_server` is a class variable set equal to `reactor.listenTCP(settings.NODE_PORT, NeoClientFactory(incoming_client=True))`.

I ran into issues where the os.devnull opening by twisted is not closed and then I couldn't `deepcopy` NodeLeader for a later test.

**How did you solve this problem?**
Trial and Error

**How did you make sure your solution works?**
Unittest

**Are there any special changes in the code that we should be aware of?**
No

**Please check the following, if applicable:**

- [x] Did you add any tests?
- [x] Did you run `make lint`?
- [x] Did you run `make test`?
- [ ] Are you making a PR to a feature branch or development rather than master?
- [ ] Did you add an entry to `CHANGELOG.rst`? (if not, please do)

### CODE REVIEW

**Comment by ixje** [comment]
I really appreciate your willingness to help but for this PR I'm going to re-write the tests and do it myself. There's a couple of reasons for it;
- It's far easier to reason why a test exists when I've written it myself then to review tests from others 
- For this PR coverage is secondary, whereas scenario testing is far more important. I've modified a lot of parts based on testing/scenario's I've personally encountered. Transferring this knowledge properly isn't going be efficient or likely to be fully accurate. There's simply going to be a loss of information when transferring like in any form of communication, but here I think it can be critical.  
- The current way of testing is far from optimal. For one there's a special Twisted test framework such that we shouldn't need to patch out so many internal calls. Second, I expect that I probably will have to write some simulation client to do what I want. I don't have a fully clear view on the needs yet, so another reason why transferring isn't a good idea.

w.r.t accept incoming peers. As said before (https://github.com/CityOfZion/neo-python/issues/721#issuecomment-439818242) I'm not going to work on that until the basic networking is stable.

**Comment by jseagrave21** [comment]
Okay, sounds good.

**Comment by jseagrave21** [comment]
@ixje Do you think you might want to use my tests for inspiration or should I delete the branch?

**Comment by ixje** [comment]
Can't say for now, but if you could leave them open I can always see if there's something I can quickly re-use. thanks

**Pull request closed without merging**
