### PR TITLE
improve user input for prompt with DEBUG output

### PR DESCRIPTION
**Pull request by jseagrave21**
**What current issue(s) does this address, or what feature is it adding?**
- instead of doing nothing, KeyboardInterrupt now mutes stdout while the user inputs a command
- this is especially useful while `config output` includes any DEBUG setting

- in support of https://github.com/CityOfZion/neo-python/pull/930

**How did you solve this problem?**
took cuing from `config output`

**How did you make sure your solution works?**
manual testing

**Are there any special changes in the code that we should be aware of?**
No

**Please check the following, if applicable:**

- [ ] Did you add any tests?
- [x] Did you run `make lint`?
- [ ] Did you run `make test`?

### CODE REVIEW

**Comment by ixje** [comment]
nice!! Really handy intermediate solution until we stop using this garbage `prompt_toolkit` package.
I wonder if we should maybe add a little notification indicating that we temporarily suppressed logging output for the next command, what do you think?

**Comment by jseagrave21** [comment]
Sounds good to me. I had thought about adding one originally and then decided to float the idea for your review using this minimalist version.

**Comment by jseagrave21** [comment]
Okay, I will complete this after work today.

**Comment by jseagrave21** [comment]
closed for https://github.com/ixje/neo-python/pull/11

**Pull request closed without merging**
